version: '3.1'

services:
  
  db:
    image: mysql:5.7.16
    container_name: database
    restart: always
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./mysql:/var/lib/mysql
      
  rails:
    build: 
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: simplecms
    environment:
      - DATABASE_PASSWORD=docker
      - TERM=xterm
    volumes:
      - .:/home/simplecms
    ports:
      - "3000:3000" 
      - "3001:3001"
    links:
      - db