version: '3.1'

services:
  
  db:
    image: mysql:5.7.16
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./mysql:/var/lib/mysql
      
  rails:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: simplecms
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/home/simplecms
    ports:
      - "3000:3000"
    links:     
      - db
